apiVersion: v1
data: 
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQllqQ0NBUWdDQVFBd01ERXVN
Q3dHQTFVRUF4TWxiWGt0Y0c5a0xtMTVMVzVoYldWemNHRmpaUzV3YjJRdQpZMngxYzNSbGNpNXNi
Mk5oYkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkFDb3IrcTdNNlVxCmhpTUpm
bFp4S09BZFFCMkhKNTJEaFJKdTlnYWhBNTFRSm9nc3BpVGFDeWQ2MnBpLzJnWjZnb0VUZ2d4U0Fz
Q2kKSkZ5cWZXVkt6VTZnZGpCMEJna3Foa2lHOXcwQkNRNHhaekJsTUdNR0ExVWRFUVJjTUZxQ0pX
MTVMWE4yWXk1dAplUzF1WVcxbGMzQmhZMlV1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lDSlcxNUxY
QnZaQzV0ZVMxdVlXMWxjM0JoClkyVXVjRzlrTG1Oc2RYTjBaWEl1Ykc5allXeUhCTUFBQWhpSEJB
b0FJZ0l3Q2dZSUtvWkl6ajBFQXdJRFNBQXcKUlFJZ1dscHZwWHQ2eVdyVURBMnIyNTZsZW5LTklt
MFpSM0tObzRoVlNmaGpwVllDSVFENzZkRTF5Rlh4OVpKeAprK25xL0pnOTlKRHI0bUFHYzgxUndW
UnREVW1hdnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K"
  tls.key: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3VENDQWRXZ0F3SUJBZ0lVWUNLU2dwUWht
NG9UKzdRWjR4bUluMTJ1cnVNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hERWFNQmdHQTFVRUF4TVJU
WGtnUlhoaGJYQnNaU0JUYVdkdVpYSXdJQmNOTWpVd01USXhNVGN3T0RBdwpXaGdQTWpFeU5ERXlN
amd4TnpBNE1EQmFNREF4TGpBc0JnTlZCQU1USlcxNUxYQnZaQzV0ZVMxdVlXMWxjM0JoClkyVXVj
RzlrTG1Oc2RYTjBaWEl1Ykc5allXd3dXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FB
UUEKcUsvcXV6T2xLb1lqQ1g1V2NTamdIVUFkaHllZGc0VVNidllHb1FPZFVDYUlMS1lrMmdzbmV0
cVl2OW9HZW9LQgpFNElNVWdMQW9pUmNxbjFsU3MxT280SGJNSUhZTUE0R0ExVWREd0VCL3dRRUF3
SUZvREFUQmdOVkhTVUVEREFLCkJnZ3JCZ0VGQlFjREFUQU1CZ05WSFJNQkFmOEVBakFBTUIwR0Ex
VWREZ1FXQkJTWVFjU01nQzh4WDN4bDNpbWUKcUxPWE9DQnMxVEFmQmdOVkhTTUVHREFXZ0JTellN
VjN3dlBXV1lDT2dCRHd6T2tYbzQ4VDJ6QmpCZ05WSFJFRQpYREJhZ2lWdGVTMXpkbU11YlhrdGJt
RnRaWE53WVdObExuTjJZeTVqYkhWemRHVnlMbXh2WTJGc2dpVnRlUzF3CmIyUXViWGt0Ym1GdFpY
TndZV05sTG5CdlpDNWpiSFZ6ZEdWeUxteHZZMkZzaHdUQUFBSVlod1FLQUNJQ01BMEcKQ1NxR1NJ
YjNEUUVCQ3dVQUE0SUJBUUJSTEM4c2xKb2w4S2M0M2VMZTNXek9tZ1pWNERIS1ZydG9RUXNweEtp
QwpLNXRBalVzT0RqSFVSK3NBTTRsdmxsdTl0WjY2dkd5YThzSTEyRTJFOVBOWnQvUUJEYkdZbjND
Zk9RUWRNWXRCCndlZ0llRGxMYWhjVEpmZlE2M3ZEYjBxdDJTcmY3YkM4MFhKNVJ4RSsybGtpN3BO
Y3lQWjRQODF1WmEwZU9kOWgKdzlrcHpJakF4NjJoRkNPRjh0TVc1V21sZVNHV3BEdzJQTlQ1N3A3
QUpkbmF1RHZkQ3VGb2tFYzF4UjlsUFkxVwoxY2VibjJIdEFHTWRPV1MzNmw4bUdOakxFTVhlaklK
b3JBWGFOa0E0eHpqdG1KTGNWNkt4aE42V1p6aFFETWp3CkNIY25jRWdGMTFzTTZIYlJGNTgvKytv
Tld6cHVSTDBzK1F3WWUrRFZUbEM2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
kind: Secret
metadata: 
  name: my-tls-secret
  namespace: kubernetes-dashboard
type: kubernetes.io/tls
